INSERT INTO departments (name) VALUES ('Atlántida');
INSERT INTO departments (name) VALUES ('Colón');
INSERT INTO departments (name) VALUES ('Comayagua');
INSERT INTO departments (name) VALUES ('Copán');
INSERT INTO departments (name) VALUES ('Cortés');
INSERT INTO departments (name) VALUES ('Choluteca');
INSERT INTO departments (name) VALUES ('El Paraíso');
INSERT INTO departments (name) VALUES ('Francisco Morazán');
INSERT INTO departments (name) VALUES ('Gracias a Dios');
INSERT INTO departments (name) VALUES ('Intibucá');
INSERT INTO departments (name) VALUES ('Islas de la Bahía');
INSERT INTO departments (name) VALUES ('La Paz');
INSERT INTO departments (name) VALUES ('Lempira');
INSERT INTO departments (name) VALUES ('Ocotepeque');
INSERT INTO departments (name) VALUES ('Olancho');
INSERT INTO departments (name) VALUES ('Santa Bárbara');
INSERT INTO departments (name) VALUES ('Valle');
INSERT INTO departments (name) VALUES ('Yoro');