CREATE TABLE gender
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             varchar(30),
    primary key (id)
);

INSERT INTO gender (name) VALUES ('Masculino');
INSERT INTO gender (name) VALUES ('Femenino');